<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyApp.Server\MyApp.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\MyApp.Server\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\MyApp.Server\appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
